version: '3.8'
services:
  postgres:
    container_name: QuestionPostgres
    image: postgres:14.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - QUESTION_DB_USER=docker
      - QUESTION_DB_PASSWORD=docker
      - QUESTION_DB_NAME=question
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'

  app:
    container_name: QuestionServiceApp
    build:
      context: Question/QuestionService
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/question
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - '8082:8080'
